### ISSUE TITLE
SemVer Docker images missing

### ISSUE THREAD

**Issue by jason-fox** [ging/fiware-draco#28]
@anmunoz - According to https://github.com/ging/fiware-draco/tags versions 1.3.2 and 1.3.3 have been released, however there have been no new docker pushes since 1.3.1: https://hub.docker.com/r/ging/fiware-draco/tags

Could you build and push **ging/fiware-draco:1.3.2** and **ging/fiware-draco:1.3.3** to docker hub please.

**Comment by anmunoz** [comment]
Hi, the docker images have been updated, now you have access to the ging/fiware-draco:1.3.2 and ging/fiware-draco:1.3.3 images. Can we close this issue?
