### ISSUE TITLE
[SHOULD] Every GE should have tutorial information

### ISSUE THREAD

**Issue by jason-fox** [ging/fiware-draco#3]
At the moment Draco has no information in the Academy and does not minimum Training section requirements for a Full GE. This is a placeholder to ensure a simple Draco hello world gets added to the Step-by-Step tutorials at some point

* Presence of a tutorial is a SHOULD requirement it will be upgraded in the future

An incubated GE should be working to fulfilling these requirements

**Comment by jason-fox** [comment]
As mentioned in the other issue, it is acceptable for an **Incubated** Enabler to have gaps. Yes this needs to be added at some point.

The easiest way to create a proper step-by-step tutorial would be to clone the existing Historic Context [Tutorial](https://github.com/Fiware/tutorials.Historic-Context) and replace the usage of **Cygnus** with Draco.

The tutorial just needs to focus on the **interfaces** and how to get the data from Orion into one (or more) databases via **Draco**. The setting up of the NIFI elements doesn't need to be described, the documentation already does that, but the docker container should come up with the necessary pipeline (or pipelines) instantiated.

**Comment by anmunoz** [comment]
Hi @jason-fox ,

I am preparing the tutorials for Draco and I want to know what is the procedure for publishing it?, Have I make a pull request? to What is the repository?
