### ISSUE TITLE
[SHOULD] Work towards fulfilling the requirements for a full GE

### ISSUE THREAD

**Issue by jason-fox** [ging/fiware-draco#4]
The following MUST requirements for full GE status are not currently satisfied:

Missing Badges:

* README Badge - CI Build/Unit Test (Travis)

Missing items within the README

* README - QA Section
* README - Training Section
* README - ToC
* README - How to Deploy text present
* README - How to Run Tests text present
* README - Main API Walkthrough text present
* README - Access to the advanced API and Documentation text present

Missing Release Item

* Releases uses SemVer 
(note the existing `FIWARE_7.5` tag satisfies alignment for FIWARE releases)

Missing Docker Items

* DOCKER - SemVer Image Available
* DOCKER - FIWARE Image Available

No CREDITS file

An incubated enabler should be working to fulfilling these requirements

SHOULD requirement from the TSC

**Comment by anmunoz** [comment]
Hi @jason-fox,
Where can I find the links for QA Section about Draco?

**Comment by anmunoz** [comment]
Hi @jason-fox ,
 I have been checking the requirements and I will answered with the modifications:

Missing Badges:

    README Badge - CI Build/Unit Test (Travis)----(Pending)

Missing items within the README

    README - QA Section (Included but TBD waiting for the QA team)
    README - Training Section (Included but waiting for the tutorial in Fiware academy)
    README - ToC ---- Done
    README - How to Deploy text present --- Done
    README - How to Run Tests text present----- Done
    README - Main API Walkthrough text present-- Done
    README - Access to the advanced API and Documentation text present--- Done

Missing Release Item

    Releases uses SemVer (Please clarify I don't now what I have to do here)
    (note the existing FIWARE_7.5 tag satisfies alignment for FIWARE releases)

Missing Docker Items

    DOCKER - SemVer Image Available (Please clarify I don't now what I have to do here)
    DOCKER - FIWARE Image Available (Please clarify I don't now what I have to do here)

No CREDITS file ----- Included and done

**Comment by jason-fox** [comment]
> ```
> README Badge - CI Build/Unit Test (Travis)----(Pending)
> ```

Its fine for an **Incubated** enabler to be pending items, they will need to be completed before applying for **Full Member** status.

> ```
> README - QA Section (Included but TBD waiting for the QA team)
> README - Training Section (Included but waiting for the tutorial in Fiware academy)
>```

The QA section will fill automatically once the  values are available. Personally I would have waited until they are available myself. For the training part, do you have slides or a video you could contribute to the [Academy](https://github.com/Fiware/academy) - if so just make a PR and/or raise an issue to get it included. 

>``` 
>README - ToC ---- Done
> README - How to Deploy text present --- Done
> README - How to Run Tests text present----- Done
> README - Main API Walkthrough text present-- Done
> README - Access to the advanced API and Documentation text present--- Done
> ```
 
Great.

> ```
> Releases uses SemVer (Please clarify I don't now what I have to do here)
> (note the existing FIWARE_7.5 tag satisfies alignment for FIWARE releases)
> ```

Looking at the [releases](https://github.com/ging/fiware-draco/releases) tab, you have one release called `FIWARE_7.5` which is (actually just a tag under the hood) - this isn't a SemVer tag, its just a marker for the overall FIWARE release.A semantic release version would be `major.minor.build` - e.g. 1.0.0

All you need to do is to add another tag to 0c35a1d with the appropriate version number.
You can see an example [here](https://github.com/ging/fiware-idm/tags)

> ```
> DOCKER - SemVer Image Available (Please clarify I don't now what I have to do here)
> DOCKER - FIWARE Image Available (Please clarify I don't now what I have to do here)
> ```

If you go to Docker Hub [Draco](https://hub.docker.com/r/ging/fiware-draco/tags) is only offering the `latest` build, compare this with [Keyrock](https://hub.docker.com/r/fiware/idm/tags) which has tags for each FIWARE Release and each semver release.

You just need to checkout the code at 0c35a1d , build the versioned docker container and push to Docker Hub

```console
docker build -t fiware-draco:FIWARE_7.5.1 .
docker login
docker push fiware-draco:FIWARE_7.5.1
```

and repeat for the semVer version.
