### ISSUE TITLE
Droco data in mysql garbled issue

### ISSUE THREAD

**Issue by jiuaige** [ging/fiware-draco#54]
{
    "type": "Room",
    "id": "DC_S1-D41",
    "temperature": {
      "value": "打麻将1",
      "type": "Number",
      "metadata": {}
    }
 }

This is the entity in ngsi，I listened the attr of value
When the data of the table data enters mysql
But there is a issue of garbled data like this:
![image](https://user-images.githubusercontent.com/20938790/133226081-e3e8f0bc-fea7-40cc-8667-0e757ae46a5d.png)

How can i do to solve this iesue
Thank you guards,please me
Or tell me your skype number
And we can communicate it

**Comment by anmunoz** [comment]
Hi,

I can see that the problem shows when you use the value of the value field with some special characters. I think this is not a problem with the processor, but the configuration of the table regarding to the encoding and collation, please check the link https://stackoverflow.com/questions/9352404/mysql-with-japanese-characters. This link can provide you some clues about how you can solve it.

Best regards,
